/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ctrlMaestro;
import Modelo.tbMaestro;
import javax.swing.JLabel;

/**
 *
 * @author raule
 */
public class CrudMaestro extends javax.swing.JFrame {

    /**
     * Creates new form CrudMaestro
     */
    public CrudMaestro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public static void initMaestro(){
        tbMaestro modelo = new tbMaestro();
        CrudMaestro vista = new CrudMaestro();
        ctrlMaestro controlador = new ctrlMaestro(vista, modelo);
        
        vista.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCorreo = new Vista.txtComponentePorfavorProfeCompileAntes();
        txtNombre = new Vista.txtComponentePorfavorProfeCompileAntes();
        txtEdad = new Vista.txtComponentePorfavorProfeCompileAntes();
        txtPeso = new Vista.txtComponentePorfavorProfeCompileAntes();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMaestros = new javax.swing.JTable();
        btnLimpiar = new Vista.ButtonPrueba();
        btnAgregar = new Vista.ButtonPrueba();
        btnActualizar = new Vista.ButtonPrueba();
        btnBorrar = new Vista.ButtonPrueba();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel1.setText("CRUD para Maestros");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        txtCorreo.setBackground(new java.awt.Color(0, 0, 102));
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCorreo.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtCorreo.setLabelText("Correo del maestro");
        txtCorreo.setLineColor(new java.awt.Color(255, 255, 255));
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 230, -1));

        txtNombre.setBackground(new java.awt.Color(0, 0, 102));
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNombre.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtNombre.setLabelText("Nombre del maestro");
        txtNombre.setLineColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 230, -1));

        txtEdad.setBackground(new java.awt.Color(0, 0, 102));
        txtEdad.setForeground(new java.awt.Color(255, 255, 255));
        txtEdad.setCaretColor(new java.awt.Color(255, 255, 255));
        txtEdad.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtEdad.setLabelText("Edad del maestro");
        txtEdad.setLineColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 230, -1));

        txtPeso.setBackground(new java.awt.Color(0, 0, 102));
        txtPeso.setForeground(new java.awt.Color(255, 255, 255));
        txtPeso.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPeso.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtPeso.setLabelText("Peso del maestro");
        txtPeso.setLineColor(new java.awt.Color(255, 255, 255));
        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });
        jPanel1.add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 230, -1));

        tbMaestros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbMaestros);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 1000, 340));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnLimpiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 200, 60));

        btnAgregar.setText("Agregar");
        btnAgregar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 200, 60));

        btnActualizar.setText("Actualizar");
        btnActualizar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnActualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 200, 60));

        btnBorrar.setText("Borrar");
        btnBorrar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnBorrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 200, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                initMaestro();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public Vista.ButtonPrueba btnActualizar;
    public Vista.ButtonPrueba btnAgregar;
    public Vista.ButtonPrueba btnBorrar;
    public Vista.ButtonPrueba btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tbMaestros;
    public Vista.txtComponentePorfavorProfeCompileAntes txtCorreo;
    public Vista.txtComponentePorfavorProfeCompileAntes txtEdad;
    public Vista.txtComponentePorfavorProfeCompileAntes txtNombre;
    public Vista.txtComponentePorfavorProfeCompileAntes txtPeso;
    // End of variables declaration//GEN-END:variables
}
